Repository openlitedotdev/CLearn, pull requests merged in 2025-03, with the labels that each got.

#3 Update guide local development
  README.md
Labels: documentation

#7 docs: add issue statement and license type
  README.md
Labels: documentation

#6 feat: create TheNav component
  app/app.vue
  app/components/TheNav.vue
  app/components/form/Input.vue
  app/components/option/Drowpdown.vue
  app/layouts/default.vue
  app/pages/index.vue
  nuxt.config.ts
  package.json
  pnpm-lock.yaml
  public/logo.svg
Labels: enhancement

#14 feat: add lang selection and improve dark mode
  app/components/TheNav.vue
  app/components/display/Skeleton.vue
  app/components/panel/DarkMode.vue
  app/components/panel/SelectLang.vue
  app/composables/darkMode.ts
  app/layouts/default.vue
  uno.config.ts
Labels: good first issue
